### ISSUE TITLE
Track wasted food

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#11]
As a **user** I can **track wasted food** so that **I know how much food was wasted**.

### Acceptance criteria:
- When delete an item from the inventory, user can select "consumed" or "wasted".
- A table or list displays all the wasted items, including their names, quantities,  and date when they were wasted.

### Tasks:
- [ ] Provide 'Consume' and 'Throw away' options/ buttons for each item.
- [ ] Add count function for items which have been thrown away.
- [ ] Display a message/ summary about how many items have been wasted on the dashboard page. 
- [ ] Add a 'View details' button to the summary and display a detailed list of wasted items when the button is clicked.
