### ISSUE TITLE
Display success messages

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#12]
As a **user** I can **see success messages** so that **I know when I successfully added, updated and deleted an item**.

### Acceptance criteria:
- Display a success message when an item is added
- Display a success message when an item is updated
- Display a success message when an item is deleted

### Tasks:
- [x] Display success messages with item's name
- [x] Users can close the messages once they've seen it
- [x] Display a modal window when users click 'delete' button. asking for confirmation
