### ISSUE TITLE
User logout

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#18]
As a **registered user** I can **log out of my account** so that **I can securely end my session and protect my personal information**.

### Acceptance criteria:
- Acceptance criteria 1: The user can see a clearly labeled "Logout" button on the dashboard and other pages when they are logged in.
- Acceptance criteria 2: Upon clicking the "Logout" button, the user is logged out of their account, and the session is terminated.
- Acceptance criteria 3: After logging out, the user is redirected to the homepage or a login page with a confirmation message indicating a successful logout.
- Acceptance criteria 4: Once logged out, the user should not be able to access any authenticated pages (like the dashboard or account settings) without logging back in.

### Tasks:
- [x] Add a logout button next to the user's profile icon
- [x] Display a message showing user has been logged out
- [x] Add two buttons for redirection after user logged out: **Log back in** and **Back to home page**
