### ISSUE TITLE
Add Items to the Inventory

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#4]
As a **user** I can **add items to my fridge and freezer inventory** so that **I can keep track of what I have**.

### Acceptance criteria:
- User can navigate to an 'Add Item' button/ section.
- User can provide item name, category, best-before date, and location (fridge/freezer compartment).
- User can see a message when they successfully add an item.
- User can see the new item in their inventory list after adding it.

### Tasks:
- [x] Display a form for users to fill out to create a new item when users click "Add item" button
- [x] Display a message to tell users when the new item is created successfully.
- [x] Display the newly created item in the inventory list.
