### ISSUE TITLE
Edit an Item in the inventory

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#5]
As a **user** I can **edit details of an item in my inventory** so that **I can keep the information up-to-date**.

### Acceptance criteria:
- User can navigate to an 'Edit Item' button from the inventory list.
- User can update item name, category, expiry date, and location.
- User can see a message when they successfully update an item.
- Changes are reflected in the inventory list after saving.

### Tasks:
- [x] Add an 'Edit' button to each item
- [x] Display a form for user to edit the item based on existing details
- [x] Display a message when item is updated successfully
- [x] Update inventory table with updated items.
