### ISSUE TITLE
Search items in the inventory

### ISSUE THREAD

**Issue by CrazyEggz** [CrazyEggz/ci-fridge-pal#8]
As a **user** I can **search for items in my inventory according to various criteria** so that **I can view and manage items more easily**.

### Acceptance criteria:
- User can use a search bar with various criteria on the inventory page to search items
- Use of the search bar is intuitive
- Inventory table gets updated according to user's search criteria 

### Tasks:
- [x] Create a search bar with multiple fields of search criteria
- [x] Provide a dropdown menu for each search field that allows users to select from
- [x] Add a 'Search' button
- [x] Update the inventory table according to user's search criteria
